### ISSUE TITLE
Method 'MeasureText' in type 'NControl.Win.CanvasCanvas' from assembly 'NControl.WP80 (...) does not have an implementation.

### ISSUE THREAD

**Issue by peneves** [chrfalch/NControl#37]
So, to reproduce:
1 - Create a Xamarin.Forms portable project (i'm using VS2013)
2 - Install ncontrol and ngraphics on WP and portable
3 - Create any NControlView on XAML or CS page in forms

I'm using Init() just as you do on your sample for WP8.0. And your sample does work on my phone. I just can't reproduce. I already confirmed I'm using all the same versions of every nugget package in both.

Thanks.
-       $exception  {System.TypeLoadException: Method 'MeasureText' in type 'NControl.Win.CanvasCanvas' from assembly 'NControl.WP80, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
  at NControl.WP80.NControlViewRenderer.CreateCanvas(Canvas canvas)
  at NControl.Win.NControlViewRendererBase.RedrawControl()
  at NControl.Win.NControlViewRendererBase.OnElementPropertyChanged(Object sender, PropertyChangedEventArgs e)
  at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
  at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
  at Xamarin.Forms.BindableObject.OnPropertyChanged(String propertyName)
  at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
  at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
  at Xamarin.Forms.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
  at Xamarin.Forms.BindableObject.SetValue(BindablePropertyKey propertyKey, Object value)
  at Xamarin.Forms.VisualElement.set_Height(Double value)
  at Xamarin.Forms.VisualElement.SetSize(Double width, Double height)
  at Xamarin.Forms.VisualElement.set_Bounds(Rectangle value)
  at Xamarin.Forms.VisualElement.Layout(Rectangle bounds)
  at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion(VisualElement child, Rectangle region, SizeRequest childSizeRequest)
  at Xamarin.Forms.StackLayout.LayoutChildren(Double x, Double y, Double width, Double height)
  at Xamarin.Forms.Layout.UpdateChildrenLayout()
  at Xamarin.Forms.Layout.OnSizeAllocated(Double width, Double height)
  at Xamarin.Forms.VisualElement.SizeAllocated(Double width, Double height)
  at Xamarin.Forms.Layout.OnChildMeasureInvalidated()
  at Xamarin.Forms.Layout.OnChildMeasureInvalidated(Object sender, EventArgs e)
  at Xamarin.Forms.VisualElement.InvalidateMeasure()
  at Xamarin.Forms.VisualElement.set_IsNativeStateConsistent(Boolean value)
  at Xamarin.Forms.Platform.WinPhone.VisualElementRenderer`2.<SetNativeControl>b__1(Object sender, RoutedEventArgs args)
  at MS.Internal.CoreInvokeHandler.InvokeEventHandler(Int32 typeIndex, Delegate handlerDelegate, Object sender, Object args)
  at MS.Internal.JoltHelper.FireEvent(IntPtr unmanagedObj, IntPtr unmanagedObjArgs, Int32 argsTypeIndex, Int32 actualArgsTypeIndex, String eventName)} System.Exception {System.TypeLoadException}

**Comment by chrfalch** [comment]
Correct - NControl is not yet compatible with NGraphics 0.3.1.

**Comment by peneves** [comment]
wow, quick, thanks

**Comment by peneves** [comment]
Also, now the buttons inside the NControlView won't show any text and are always transparent. Should i open another issue?

**Comment by chrfalch** [comment]
Been waiting to do this for a while ;-)

**Comment by chrfalch** [comment]
Yes, please go ahead and to that. You can also download the sources and see
if you can help fix them?

**Comment by peneves** [comment]
I'll try, but i doubt i will do any good :/
